[build]
  publish = "public"
  command = "make production-build"

[build.environment]
  HUGO_VERSION = "0.104.0"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  HUGO_ENV = "staging"
  command = "make preview-build"

[context.branch-deploy]
  command = "make preview-build"

[dev]
  command = "make serve URL=http://localhost:8888/"
  framework = "hugo"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  todoPatterns = ["load", "fragment"]
  checkExternal = false
  followSourceMaps = true
