# Each YAML file under sync/ configures how helper/helper.py synchronizes
# contents of various versions from its source of truth (usually a GitHub
# repository of a Tekton component, such as tektoncd/pipelines) to
# content/ (for the lastest version) and vault/ (for earlier versions).

# The name of the component.
# helper.py will use this value to build directories in content/ and vault/.
component: Triggers
# The order of the component.
displayOrder: 1
# The GitHub repository where documentation resides.
repository: https://github.com/tektoncd/triggers
# The directory in the GitHub repository where contents reside.
docDirectory: docs
# The tags (versions) of contents to sync.
# Note that helper.py and related script reads tags in the order specified in
# the following list; the first entry in tags will automatically become the
# latest version of contents.
tags:
  # The name of the tag in the GitHub repository.
- name: master
  # The name to display on tekton.dev.
  # helper.py will use this value in the version switcher and other places.
  displayName: master
  # Key-value pairs of files to sync, where the key is the original filename
  # and the value is the new filename.
  files:
  - README.md: _index.md
  - eventlisteners.md: eventlisteners.md
  - exposing-eventlisteners.md: exposing-eventlisteners.md
  - install.md: install.md
  - triggerbindings.md: triggerbindings.md
  - triggertemplates.md: triggertemplates.md
  - clustertriggerbindings.md: clustertriggerbindings.md
  - cel_expressions.md: cel_expressions.md
  - create-ingress.yaml: create-ingress.yaml
  - create-webhook.yaml: create-webhook.yaml
# The link to the GitHub tag page.
archive: https://github.com/tektoncd/triggers/tags
