# Each YAML file under sync/ configures how sync/sync.py synchronizes
# contents of various versions from its source of truth (usually a GitHub
# repository of a Tekton component, such as tektoncd/pipelines) to
# content/ (for the lastest version) and vault/ (for earlier versions).

# The name of the component.
# sync.py will use this value to build directories in content/ and vault/.
component: Triggers
# The order of the component.
displayOrder: 1
# The GitHub repository where documentation resides.
repository: https://github.com/tektoncd/triggers
# The directory in the GitHub repository where contents reside.
docDirectory: docs
# The link to the GitHub tag page.
archive: https://github.com/tektoncd/triggers/tags
# The tags (versions) of contents to sync.
# Note that sync.py and related script reads tags in the order specified in
# the following list; the first entry in tags will automatically become the
# latest version of contents.
# To add a new version, append to the list as below
# - name: vX.Y.Z
#   displayName: vX.Y.Z
#   folders:
#     docs:
#       target: '/'            # optional, default value '/'
#       index: README.md       # optional, if _index.md exists
#       include: ['*.md']      # optional, default value ['*']
#       exclude: ['not_in.md'] # optional, default value []
#       header: <dict>         # optional, no header added if not set
#         See https://www.docsy.dev/docs/adding-content/navigation/#section-menu
tags:
- name: v0.10.1
  # The name to display on tekton.dev.
  # sync.py will use this value in the version switcher and other places.
  displayName: v0.10.1
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/getting-started:
      target: getting-started
      include:
      - create-ingress.yaml
      - create-webhook.yaml
- name: v0.9.1
  # The name to display on tekton.dev.
  # sync.py will use this value in the version switcher and other places.
  displayName: v0.9.1
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/getting-started:
      target: getting-started
      include:
      - create-ingress.yaml
      - create-webhook.yaml
- name: v0.8.1
  # The name to display on tekton.dev.
  # helper.py will use this value in the version switcher and other places.
  displayName: v0.8.1
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include: ['*.md']
      exclude: [triggers.md]
    docs/getting-started:
      target: getting-started
      include:
      - create-ingress.yaml
      - create-webhook.yaml
- name: v0.7.0
  # The name to display on tekton.dev.
  # helper.py will use this value in the version switcher and other places.
  displayName: v0.7.0
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/getting-started:
      target: ''
      include:
      - create-ingress.yaml
      - create-webhook.yaml
- name: v0.6.1
  # The name to display on tekton.dev.
  # helper.py will use this value in the version switcher and other places.
  displayName: v0.6.1
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include:
      - '*.md'
      - create-ingress.yaml
      - create-webhook.yaml
- name: main
  # The name to display on tekton.dev.
  # helper.py will use this value in the version switcher and other places.
  displayName: main
  # Dict of folders to sync
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/getting-started:
      target: getting-started
      include:
      - create-ingress.yaml
      - create-webhook.yaml
