apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-website
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/tektoncd/website

