apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-go-app-task
spec:
  resources:
    inputs:
      # Some inputs, such as your GitHub repository
      ...
  steps:
  - name: build
    image: golang
    command:
    - go
    - build
    args:
    - /workspace/myapp
